# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Virtuelab
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: virtuelab
author:
  email: admin@virtuelab.io

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
header_pages:
  - about.md

# Build settings
remote_theme: jekyll/minima
theme: minima
gems:
  - jekyll-pandoc
plugins:
  - jekyll-remote-theme #enable most recent minima to work with github pages, the plugin downloads the theme directly from this repository again each time you build your site
markdown: Pandoc
pandoc:
  extensions:
    # the following line for extensions has to be entered just as if you were passing it to pandoc on the command line. Ignore the plugin docs.
    # --metadata suppress-bibliography=true flag does not work, so I commented out the <bibliography> tag in the csl
    - --from markdown+inline_notes+all_symbols_escapable+hard_line_breaks+line_blocks+smart+citations+escaped_line_breaks+raw_tex 
    - csl: _styles/sbl.csl
    - bibliography: ~/zotero/zotero_library.bib

destination: docs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache
  - _posts
  - CNAME
